function [ all_pos_probs, all_trans_probs ] = get_sum_prod_marginals(train_size, f_params, t_params, train_data)
%GET_SUM_PROD_MARGINALS Summary of this function goes here
%   Detailed explanation goes here
all_node_potentials = arrayfun(@(i) nodePotential(f_params, cell2mat(train_data(i))), ...
    [1:train_size], 'UniformOutput', false');
all_clique_potentials = arrayfun(@(i) cliquePotentials(t_params, cell2mat(all_node_potentials(i))), ...
    [1:train_size], 'UniformOutput', false');
[all_forward_messages, all_backward_messages] = arrayfun(@(i) messages(cell2mat(all_clique_potentials(i))), ...
    [1:train_size], 'UniformOutput', false');
all_beliefs = arrayfun(@(i) calBeliefs(cell2mat(all_clique_potentials(i)),...
    cell2mat(all_forward_messages(i)),cell2mat(all_backward_messages(i))), ...
    [1:train_size], 'UniformOutput', false');
[all_pos_probs, all_trans_probs] = arrayfun(@(i) calMarginals(cell2mat(all_node_potentials(i)),cell2mat(all_beliefs(i))), ...
    [1:train_size], 'UniformOutput', false');